<?php
/**
 * Farther Horizon Site Kit
 *
 * @link       http://github.com/alanwagner/FhSiteKit for the canonical source repository
 * @copyright Copyright (c) 2013 Farther Horizon SARL (http://www.fartherhorizon.com)
 * @license   http://www.gnu.org/licenses/gpl-3.0.html GPLv3 License
 * @author    Alan Wagner (mail@alanwagner.org)
 */
?>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('siteAdmin', array('siteKey' => $this->site('path'))); ?>"><?php echo $this->site('name') ?> Admin</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="<?php echo ($this->templateNamespace == 'pattern') ? 'active' : '' ?>">
                    <a href="<?php echo $this->url('patternAdmin', array('siteKey' => $this->site('path'))) ?>"><?php echo $this->translate('Patterns') ?></a>
                </li>
                <li class="<?php echo ($this->templateNamespace == 'template') ? 'active' : '' ?>">
                    <a href="<?php echo $this->url('templateAdmin', array('siteKey' => $this->site('path'))) ?>"><?php echo $this->translate('Templates') ?></a>
                </li>
                <li class="<?php echo ($this->templateNamespace == 'instance') ? 'active' : '' ?>">
                    <a href="<?php echo $this->url('instanceAdmin', array('siteKey' => $this->site('path'))) ?>"><?php echo $this->translate('Instances') ?></a>
                </li>
                <?php if (isset($this->FhskConfig)): ?>
                <li class="<?php echo ($this->templateNamespace == 'config') ? 'active' : '' ?>">
                    <a class="<?php echo ($this->FhskConfig['keyCount'] > $this->FhskConfig['dataCount']) ? 'fhsk-alert' : '' ?>" href="<?php echo $this->url('configAdmin', array('siteKey' => $this->site('path'))) ?>"><?php echo $this->translate('Config') ?></a>
                </li>
                <?php endif;  ?>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
