<?php
/**
 * Farther Horizon Site Kit
 *
 * @link       http://github.com/alanwagner/FhSiteKit for the canonical source repository
 * @copyright Copyright (c) 2013 Farther Horizon SARL (http://www.fartherhorizon.com)
 * @license   http://www.gnu.org/licenses/gpl-3.0.html GPLv3 License
 * @author    Alan Wagner (mail@alanwagner.org)
 */

?>
<?php if (isset($this->messages)): ?>
    <div class="fhsk-block fhsk-messages">
        <?php echo $this->messages; ?>
    </div>
<?php endif; ?>
<div class="fhsk-block fhsk-headline">
    <?php echo $this->headline; ?>
</div>

<div class="fhsk-block fhsk-links">
    <?php echo $this->links; ?>
</div>

<?php if (isset($this->form)): ?>
    <div class="fhsk-block fhsk-form">
        <?php echo $this->form; ?>
    </div>
<?php endif; ?>

<div class="fhsk-block fhsk-data">
    <?php echo $this->data; ?>
</div>
