<?php
/**
 * Farther Horizon Site Kit
 *
 * @link       http://github.com/alanwagner/FhSiteKit for the canonical source repository
 * @copyright Copyright (c) 2013 Farther Horizon SARL (http://www.fartherhorizon.com)
 * @license   http://www.gnu.org/licenses/gpl-3.0.html GPLv3 License
 * @author    Alan Wagner (mail@alanwagner.org)
 */
?>

<table class="table">
<tr>
<th>Id</th>
<th>Name</th>
<th>Description</th>
<th>Status</th>
<th>Pattern Name</th>
<th>&nbsp;</th>
</tr>
<?php foreach ($this->instances as $instance) : ?>
<tr class="fhsk-hover">
    <td><?php echo $this->escapeHtml($instance->id);?></td>
    <td><?php echo $this->escapeHtml($instance->name);?></td>
    <td><?php echo nl2br($this->escapeHtml($instance->description));?></td>
    <td><?php echo $this->escapeHtml($instance->status);?></td>
    <td><?php echo $this->escapeHtml($instance->pattern_name);?></td>
    <td class="actionLinks">
        <a href="<?php echo $this->url('instanceAdmin',
            array('siteKey' => $this->site('path'), 'action'=>'view', 'id' => $instance->id));?>">View</a>
        <a href="<?php echo $this->url('instanceAdmin',
            array('siteKey' => $this->site('path'), 'id' => $instance->id, 'action' => 'toggle-archived', 'returnAction' => $this->routeAction));?>"><?php if (empty($instance->is_archived)): ?>Archive<?php else: ?>Unarchive<?php endif; ?></a>
    </td>
</tr>
<?php endforeach; ?>
</table>
