<?php
/**
 * Farther Horizon Site Kit
 *
 * @link       http://github.com/alanwagner/FHSK for the canonical source repository
 * @copyright Copyright (c) 2013 Farther Horizon SARL (http://www.fartherhorizon.com)
 * @license   http://www.gnu.org/licenses/gpl-3.0.html GPLv3 License
 * @author    Alan Wagner (mail@alanwagner.org)
 */
?>

<table class="table">
<tr>
<th>Id</th>
<th>Name</th>
<th>&nbsp;</th>
</tr>
<?php foreach ($patterns as $pattern) : ?>
<tr>
    <td><?php echo $this->escapeHtml($pattern->id);?></td>
    <td><?php echo $this->escapeHtml($pattern->name);?></td>
    <td>
        <a href="<?php echo $this->url('patternAdmin',
            array('siteKey' => $this->site('path'), 'action'=>'edit', 'id' => $pattern->id));?>">Edit</a>
        <a href="<?php echo $this->url('patternAdmin',
            array('siteKey' => $this->site('path'), 'action'=>'add', 'id' => $pattern->id));?>">Clone</a>
        <a href="<?php echo $this->url('patternAdmin',
            array('siteKey' => $this->site('path'), 'id' => $pattern->id, 'action' => 'toggle-archived', 'returnAction' => $this->routeAction));?>"><?php if (empty($pattern->is_archived)): ?>Archive<?php else: ?>Unarchive<?php endif; ?></a>
    </td>
</tr>
<?php endforeach; ?>
</table>