<?php
/**
 * Farther Horizon Site Kit
 *
 * @link       http://github.com/alanwagner/FhSiteKit for the canonical source repository
 * @copyright Copyright (c) 2013 Farther Horizon SARL (http://www.fartherhorizon.com)
 * @license   http://www.gnu.org/licenses/gpl-3.0.html GPLv3 License
 * @author    Alan Wagner (mail@alanwagner.org)
 */
?>
<p>In a one-shot pattern, the <strong>Player Node is always node #1:</strong><br /></p>
<pre>
One-shot with 5 neighbors and N total nodes:

1
2  1
3  1
4  1
5  1
6  1
7
8
9
10
....
N
</pre>
