<?php
/**
 * Farther Horizon Site Kit
 *
 * @link       http://github.com/alanwagner/FhSiteKit for the canonical source repository
 * @copyright Copyright (c) 2013 Farther Horizon SARL (http://www.fartherhorizon.com)
 * @license   http://www.gnu.org/licenses/gpl-3.0.html GPLv3 License
 * @author    Alan Wagner (mail@alanwagner.org)
 */
?>

<table class="table">
<tr>
<th>Key</th>
<th>Value</th>
<th>&nbsp;</th>
</tr>
<?php foreach ($this->configArray as $configKey => $configValue) : ?>
<tr class="fhsk-hover">
    <td class="<?php echo ($configValue === '') ? 'fhsk-alert' : '' ?>">
        <?php echo $this->escapeHtml($configKey);?>
    </td>
    <td><?php echo $this->escapeHtml($configValue); ?></td>
    <td class="actionLinks">
        <a href="<?php echo $this->url('configAdmin',
            array('siteKey' => $this->site('path'), 'action'=>'configure', 'configKey' => $configKey));?>">Configure</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
