<?php
/**
 * Farther Horizon Site Kit
 *
 * @link       http://github.com/alanwagner/FhSiteKit for the canonical source repository
 * @copyright Copyright (c) 2013 Farther Horizon SARL (http://www.fartherhorizon.com)
 * @license   http://www.gnu.org/licenses/gpl-3.0.html GPLv3 License
 * @author    Alan Wagner (mail@alanwagner.org)
 */
?>
<p>In the Instance Name:</p>

<p>
Use <strong># ## ###</strong> to inject the template serial number.<br />
#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;= plain number<br />
##&nbsp;&nbsp;&nbsp;= 2-digit number, zero-filled<br />
###&nbsp;= 3-digit number, zero-filled<br />
</p>

<p>
Use <strong>#pattern</strong> to inject the current pattern name.
</p>

<p>For example:<br />
4.##  SingleGirl - #pattern<br />
Might give you:<br />
4.07  SingleGirl - 24-node Lattice<br />
</p>

