<?php
/**
 * Farther Horizon Site Kit
 *
 * @link       http://github.com/alanwagner/FHSK for the canonical source repository
 * @copyright Copyright (c) 2013 Farther Horizon SARL (http://www.fartherhorizon.com)
 * @license   http://www.gnu.org/licenses/gpl-3.0.html GPLv3 License
 * @author    Alan Wagner (mail@alanwagner.org)
 */
?>

<table class="table">
<tr>
<th>Id</th>
<th>Name</th>
<th>Pattern</th>
<th>Instance&nbsp;Name</th>
<th>Description</th>
<th>&nbsp;</th>
</tr>
<?php foreach ($templatesData as $templateData) : ?>
<tr class="fhsk-hover">
    <td rowspan="2"><?php echo $this->escapeHtml($templateData->id);?></td>
    <td><?php echo $this->escapeHtml($templateData->name);?></td>
    <td><a href="javascript:void(0)" onclick="$('#pattern-content-<?php echo $templateData->id ?>').animate({height: 'toggle'}, 500)"><?php echo $this->escapeHtml($templateData->pattern__name);?></a></td>
    <td><?php echo $this->escapeHtml($templateData->instance_name);?></td>
    <td><?php echo nl2br($this->escapeHtml($templateData->description));?></td>
    <td class="actionLinks">
        <a href="<?php echo $this->url('templateAdmin',
            array('siteKey' => $this->site('path'), 'action'=>'edit', 'id' => $templateData->id));?>">Edit</a>
        <a href="<?php echo $this->url('templateAdmin',
            array('siteKey' => $this->site('path'), 'action'=>'add', 'id' => $templateData->id));?>">Clone</a>
        <a href="<?php echo $this->url('templateAdmin',
            array('siteKey' => $this->site('path'), 'id' => $templateData->id, 'action' => 'toggle-archived', 'returnAction' => $this->routeAction));?>"><?php if (empty($templateData->is_archived)): ?>Archive<?php else: ?>Unarchive<?php endif; ?></a>
        <a href="javascript:void(0)">Spawn</a>
    </td>
</tr>
<tr class="fhsk-hover fhsk-hover-too">
    <td colspan="5" class="noTopBorder"><div class="pattern-content" id="pattern-content-<?php echo $templateData->id ?>"><pre><?php echo $templateData->pattern__content ?></pre></div></td>
</tr>
<?php endforeach; ?>
</table>
