<?php
/**
 * Farther Horizon Site Kit
 *
 * @link       http://github.com/alanwagner/FHSK for the canonical source repository
 * @copyright Copyright (c) 2013 Farther Horizon SARL (http://www.fartherhorizon.com)
 * @license   http://www.gnu.org/licenses/gpl-3.0.html GPLv3 License
 * @author    Alan Wagner (mail@alanwagner.org)
 */

$title = sprintf('Edit %s Template %d (%s)', $this->site('name'), $this->template->id, $this->template->name);
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>