<?php
/**
 * Farther Horizon Site Kit
 *
 * @link       http://github.com/alanwagner/FhSiteKit for the canonical source repository
 * @copyright Copyright (c) 2013 Farther Horizon SARL (http://www.fartherhorizon.com)
 * @license   http://www.gnu.org/licenses/gpl-3.0.html GPLv3 License
 * @author    Alan Wagner (mail@alanwagner.org)
 */
?>

<p>
    <a href="<?php echo $this->url('templateAdmin', array('siteKey' => $this->site('path')));?>">List active templates</a>
</p>
<p>
    <a href="<?php echo $this->url('templateAdmin', array('siteKey' => $this->site('path'), 'action' => 'list-archived'));?>">List archived templates</a>
</p>
<p>
    <a href="<?php echo $this->url('templateAdmin', array('siteKey' => $this->site('path'), 'action'=>'add'));?>">Add new template</a>
</p>
