<?php
/**
 * Farther Horizon Site Kit
 *
 * @link       http://github.com/alanwagner/FhSiteKit for the canonical source repository
 * @copyright Copyright (c) 2013 Farther Horizon SARL (http://www.fartherhorizon.com)
 * @license   http://www.gnu.org/licenses/gpl-3.0.html GPLv3 License
 * @author    Alan Wagner (mail@alanwagner.org)
 */
?>

<table class="table">
<tr>
<th>Key</th>
<th>Description</th>
</tr>
<?php foreach ($this->emailArray as $emailKey => $emailData) : ?>
<tr class="fhsk-hover">
    <td>
        <a href="<?php echo $this->url('emailAdmin',
            array('siteKey' => $this->site('path'), 'action'=>'edit', 'emailKey' => $emailKey));?>">
            <?php echo $emailKey ?>
        </a>
    </td>
    <td><?php echo nl2br($this->escapeHtml(trim($emailData['description']))); ?></td>
    </tr>
<?php endforeach; ?>
</table>

