<?php
/**
 * Farther Horizon Site Kit
 *
 * @link       http://github.com/alanwagner/FhSiteKit for the canonical source repository
 * @copyright Copyright (c) 2013 Farther Horizon SARL (http://www.fartherhorizon.com)
 * @license   http://www.gnu.org/licenses/gpl-3.0.html GPLv3 License
 * @author    Alan Wagner (mail@alanwagner.org)
 */
?>

<p>
<?php echo nl2br(trim($this->emailConfig['description'])); ?>
</p>

<?php

$params = array(
    'action'  => $this->formAction,
    'siteKey' => $this->site('path'),
);
if (! empty($this->emailKey)) {
    $params['emailKey'] = $this->emailKey;
}

$form->setAttribute('action', $this->url('emailAdmin', $params));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
