<?php
/**
 * Farther Horizon Site Kit
 *
 * @link       http://github.com/alanwagner/FHSK for the canonical source repository
 * @copyright Copyright (c) 2013 Farther Horizon SARL (http://www.fartherhorizon.com)
 * @license   http://www.gnu.org/licenses/gpl-3.0.html GPLv3 License
 * @author    Alan Wagner (mail@alanwagner.org)
 */
?>

<p>This is the 'data-list' template, displayed in the 'data' block.</p>

<p>
The other blocks in this page are 'headline' and 'links' (above),
and 'site/admin/menu' in the layout 'layout/admin'.<br />
There is potentially a 'form' block above this one, as well.<br />
These are displayed in the 'page' template.
</p>
