<?php
/**
 * Farther Horizon Site Kit
 *
 * @link       http://github.com/alanwagner/FHSK for the canonical source repository
 * @copyright Copyright (c) 2013 Farther Horizon SARL (http://www.fartherhorizon.com)
 * @license   http://www.gnu.org/licenses/gpl-3.0.html GPLv3 License
 * @author    Alan Wagner (mail@alanwagner.org)
 */
?>

<?php foreach ($this->messages as $namespace => $messages): ?>
    <?php foreach ($messages as $message): ?>
        <p class="alert-<?php echo $namespace ?>"><?php echo $message; ?></p>
    <?php endforeach; ?>
<?php endforeach;
